src/Entity/WeekDay.php
<?php

namespace App\Entity;

use App\Repository\WeekDayRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WeekDayRepository::class)]
class WeekDay
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 8)]
    private ?string $name_week_day = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameWeekDay(): ?string
    {
        return $this->name_week_day;
    }

    public function setNameWeekDay(string $name_week_day): static
    {
        $this->name_week_day = $name_week_day;

        return $this;
    }
}

src/Controller/CalendarMonthlyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\WeekDayRepository;
use App\Repository\MonthRepository;


class CalendarMonthlyController extends AbstractController
{
    private $month_repository;
    private $week_day_repository;

    public function __construct(MonthRepository $monthRepository, WeekDayRepository $weekDayRepository)
    {
        $this->month_repository = $monthRepository;
        $this->week_day_repository = $weekDayRepository;
    }

    #[Route('/calendar/monthly/{monthId?}/{year?}', name: 'app_calendar_monthly')]
    public function index(Request $request): Response
    {
        // Récupère tous les noms des jours de la semaine et des mois 
        $name_days_week = $this->week_day_repository->findAll();
        $name_months = $this->month_repository->findAll();
        
        $current_date = new \DateTime();
        $days_of_month = [];

        //Récupère le mois et l'année actuels
        $current_month_number = $current_date->format('n');
        $current_year = $current_date->format('Y');

        // Récupère le mois et l'année sélectionnés à partir de la requête
        $selected_month = $request->attributes->get('monthId');
        if ($selected_month) {
            $current_month_number = $selected_month;
        }
        $selected_year = $request->attributes->get('year');
        if ($selected_year) {
            $current_year = $selected_year;
        }
        
        // Trouve le mois précédent
        $previous_month_index = ($current_month_number - 2 + 12) % 12;
        $previous_month = $name_months[$previous_month_index];
        
        // Trouve le mois suivant
        $next_month_index = ($current_month_number % 12);
        $next_month = $name_months[$next_month_index];

        // Appel de la méthode pour récupérer le nom du mois depuis MonthRepository
        $current_month_name = $this->month_repository->getMonthNameFromDb($current_month_number);

        // Appel de la méthode pour récupérer les jours du mois en cours
        $days_of_month = $this->getDaysInMonth($current_month_number, $current_year);

        // Retourne la vue avec les infos relatives à la date
        return $this->render('calendar_monthly/index.html.twig', [
            'days_of_week' => $name_days_week,
            'current_month_name' => $current_month_name,
            'days_of_month' => $days_of_month,
            'name_months' => $name_months,
            'previous_month' => $previous_month,
            'next_month' => $next_month,
            'current_year' => $current_year,
            'current_month_number' => $current_month_number
        ]);
    }

    // Récupère les jours d'un mois donné
    private function getDaysInMonth(int $month, int $year): array
    {
        $days_in_month = cal_days_in_month(CAL_GREGORIAN, $month, $year);
        $days_of_month = [];

        for ($day_number = 1; $day_number <= $days_in_month; $day_number++) {
            $current_day = new \DateTime(sprintf('%s-%s-%s', $year, $month, $day_number));
            $days_of_month[] = $current_day;
        }
        return $days_of_month;
    }
}

templates/calendar_monthly/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block body %}
<div data-controller="calendarMonthly" class="calendar-wrapper">
    <h1>Planipie</h1>

    <div class="calendar-header">
        <div class="calendar-set-date">
            <button class="btn-nav-month btn-prev" data-month="{{ previous_month.id }}"><</button>
            <h3 class="title-month" data-month={{ current_month_number }} >{{ current_month_name }}</h3>
            <button class="btn-nav-month btn-next" data-month="{{ next_month.id }}">></button>
            
            <button class="btn-nav-year btn-prev"><</button>
            <h3 class="title-year">{{current_year}}</h3>
            <button class="btn-nav-year btn-next" >></button>
        </div>
        <div class="calendar-month-week">
            <button class="btn-set-month-week">Mois</button>
            <button class="btn-set-month-week">Semaine</button>
        </div>
        <div class="calendar-size-light">
            <button class="btn-set-size-light"><i class="fa-solid fa-up-right-and-down-left-from-center"></i></button>
            <button class="btn-set-size-light"><i class="fa-solid fa-moon"></i></button>
        </div>
    </div>

    <div class="calendar">
        <div class="calendar-content">
            <div class="weekdays">
                {% for day in days_of_week %}
                    <div>{{ day.nameWeekDay }}</div>
                {% endfor %}
            </div>

            <div class="days">
                {% for day in days_of_month %}
                    <div class="day-cell" data-day="{{ day.format('Y-m-d') }}">{{ day.format('j') }}</div>
                {% endfor %}
            </div>
        </div>
        <div class="dashboard">
            <h2>Hello</h2>
        </div>
     </div>
</div>
<div class="popup-add-event" data-controller="popupAddEvent">
    <div class="popup-add-event-content">
        <button id="btn-close-popup" class="btn-close-popup">X</button>
        <form id="popup-add-event-form" class="popup-add-event-form">
        <h3 class="popup-add-event-title"></h3>
            <div class="event-form-group">
                <label for="popup-add-title">Titre :</label>
                <input type="text" id="popup-add-title" name="popup-add-title" required>
            </div>
            <div class="event-form-group">
                <label for="popup-add-desc">Description :</label>
                <textarea id="popup-add-desc" name="popup-add-desc"></textarea>
            </div>
            <div class="event-form-group">
                <label for="popup-add-event-start">Début :</label>
                <input type="datetime-local" id="popup-add-event-start" name="popup-add-event-start">
            </div>
            <div class="event-form-group">
                <label for="popup-add-event-end">Fin :</label>
                <input type="datetime-local" id="popup-add-event-end" name="popup-add-event-end">
            </div>
            <div class="event-form-group">
                <label for="popup-add-all-day">Journée entière :</label>
                <input type="checkbox" id="popup-add-all-day" name="popup-add-all-day">
            </div>
            <div class="event-form-group">
                <label for="popup-add-recurrence">Récurrence :</label>
                <input type="checkbox" id="popup-add-recurrence" name="popup-add-recurrence">
            </div>
            <div class="event-form-group">
                <label for="popup-add-recurrence-end">Fin de récurrence :</label>
                <input type="datetime-local" id="popup-add-recurrence-end" name="popup-add-recurrence_end">
            </div>
             <div class="event-form-btn">
                <button type="submit">Ajouter</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}